name: telnyx_flutter
description: A Dart package for Telnyx API.
version: 0.0.3
homepage: https://github.com/kfiross/telnyx_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
